#!/usr/bin/env python3
"""
Extract a candidate protocol summary for a named Baseus device from the pre-existing
bytecode dumps. Does NOT require androguard or the APK to be present — works from the
already-generated text dumps in docs/protocol/captures/.

Usage:
    python tools/extract_apk_model.py --name "Baseus Inspire XH1"
    python tools/extract_apk_model.py --name "Baseus Bowie MC2" --dump2 path/to/bytecode-dump2.txt

Output: prints a summary to stdout; redirect to a file to save.
"""

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
DEFAULT_DUMP1 = REPO_ROOT / "docs/protocol/captures/bytecode-dump.txt"
DEFAULT_DUMP2 = REPO_ROOT / "docs/protocol/captures/bytecode-dump2.txt"
DEFAULT_APK_LOG = REPO_ROOT / "docs/protocol/captures/apk-analysis.log"


def find_model_blocks(dump_path: Path, model_name: str):
    """
    Find all bytecode blocks containing the given model name string.
    Returns list of (class_name, method_sig, context_lines).
    """
    if not dump_path.exists():
        return []

    text = dump_path.read_text(encoding="utf-8", errors="replace")
    results = []

    # Split on class/method headers
    blocks = re.split(r"={40,}\n", text)
    for block in blocks:
        if model_name not in block:
            continue
        lines = block.strip().splitlines()
        class_name = ""
        method_sig = ""
        for line in lines[:5]:
            if line.startswith("CLASS:"):
                class_name = line.replace("CLASS:", "").strip()
            elif line.startswith("METHOD:"):
                method_sig = line.replace("METHOD:", "").strip()

        # Extract the lines around each occurrence of the model name
        for i, line in enumerate(lines):
            if model_name in line:
                start = max(0, i - 3)
                end = min(len(lines), i + 15)
                context = "\n".join(f"  {l}" for l in lines[start:end])
                results.append((class_name, method_sig, context))
    return results


def extract_const_integers(block_lines: list[str], after_model_line: int, lookahead: int = 10):
    """
    Extract const/16 and const/4 integer values from lines following a model match.
    These are potential feature IDs or mode byte candidates.
    """
    values = []
    for line in block_lines[after_model_line : after_model_line + lookahead]:
        m = re.search(r"const(?:/16|/4)?\s+\w+,\s+(0x[0-9a-fA-F]+|-?\d+)", line)
        if m:
            raw = m.group(1)
            try:
                val = int(raw, 16) if raw.startswith("0x") else int(raw)
                values.append(val)
            except ValueError:
                pass
    return values


def scan_uuid_inventory(apk_log: Path):
    """Return all UUID strings from apk-analysis.log."""
    if not apk_log.exists():
        return []
    uuids = re.findall(
        r"\$([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})",
        apk_log.read_text(encoding="utf-8", errors="replace"),
    )
    return sorted(set(uuids))


def main():
    parser = argparse.ArgumentParser(description="Extract Baseus model protocol hints from APK dumps")
    parser.add_argument("--name", required=True, help="Exact model name, e.g. 'Baseus Inspire XH1'")
    parser.add_argument("--dump1", default=str(DEFAULT_DUMP1), help="Path to bytecode-dump.txt")
    parser.add_argument("--dump2", default=str(DEFAULT_DUMP2), help="Path to bytecode-dump2.txt")
    parser.add_argument("--apk-log", default=str(DEFAULT_APK_LOG), help="Path to apk-analysis.log")
    args = parser.parse_args()

    model = args.name
    dump1 = Path(args.dump1)
    dump2 = Path(args.dump2)
    apk_log = Path(args.apk_log)

    print(f"# Extraction report: {model}")
    print(f"# Generated by tools/extract_apk_model.py")
    print()

    # --- Dispatch blocks ---
    print("## Dispatch contexts")
    print("Bytecode blocks where this model name appears:\n")
    total = 0
    for dump_path in (dump1, dump2):
        blocks = find_model_blocks(dump_path, model)
        for class_name, method_sig, context in blocks:
            total += 1
            print(f"### {dump_path.name} | {class_name}")
            print(f"    Method: {method_sig}")
            print(context)
            print()
    if total == 0:
        print(f"  [!] Model name '{model}' not found in any dump.")
        print("      Check spelling — strings must match exactly as they appear in the APK.")

    # --- Integer constants near model references ---
    print("## Integer constants extracted from dispatch blocks")
    print("(These are app-internal feature IDs, NOT BLE wire opcodes unless < 256)\n")
    all_vals = set()
    for dump_path in (dump1, dump2):
        if not dump_path.exists():
            continue
        text = dump_path.read_text(encoding="utf-8", errors="replace")
        lines = text.splitlines()
        for i, line in enumerate(lines):
            if model in line:
                vals = extract_const_integers(lines, i + 1)
                all_vals.update(vals)

    if all_vals:
        ble_candidates = sorted(v for v in all_vals if 0 < v < 256)
        large_ids = sorted(v for v in all_vals if v >= 256)
        print(f"  Single-byte candidates (< 256, plausible BLE opcodes): {[hex(v) for v in ble_candidates]}")
        print(f"  Feature IDs (>= 256, app-internal only):                {large_ids}")
    else:
        print("  [!] No const-integer instructions found near model references.")
    print()

    # --- UUID candidates ---
    print("## UUID candidates from apk-analysis.log")
    uuids = scan_uuid_inventory(apk_log)
    if uuids:
        # Highlight ae00, fae0, 02F0 families
        for uuid in uuids:
            prefix = uuid[:8].lower()
            if any(p in prefix for p in ("0000ae", "0000fa", "02f000", "53527a", "ee684b", "654b74")):
                print(f"  *** {uuid}  ← known/interesting")
            else:
                pass  # skip noise
        print()
        print("  Full UUID inventory (all DEX files combined):")
        for uuid in uuids:
            print(f"    {uuid}")
    else:
        print("  [!] apk-analysis.log not found or empty.")
    print()

    # --- Next steps ---
    print("## Suggested next steps")
    print(f"  1. Create docs/protocol/{model.lower().replace(' ', '-')}.md")
    print("     (copy structure from docs/protocol/inspire-xh1.md as template)")
    print(f"  2. Create crates/baseus-protocol/src/models/{model.lower().replace(' ', '_').replace('-', '_')}.rs")
    print("     (copy structure from crates/baseus-protocol/src/models/inspire_xh1.rs)")
    print("  3. Connect device, open nRF Connect, subscribe to notify characteristic.")
    print("     Interact with device features and capture the raw hex notifications.")
    print("  4. Update the protocol doc with confirmed byte values.")
    print("  5. Open a PR — promote model from Experimental to Verified once tested.")


if __name__ == "__main__":
    main()
